site_name: Data Caterer Documentation
site_url: https://data.catering/
repo_url: https://github.com/pflooky/data-caterer-docs
repo_name: data-caterer-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - toc.integrate
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: 'index.md'
  - Get Started: 'get-started/docker.md'
  - Setup:
    - 'setup/index.md'
    - Guide:
      - 'setup/guide/index.md'
      - Scenario:
          - First Data Generation: 'setup/guide/scenario/first-data-generation.md'
          - Multiple Records Per Column Value: 'setup/guide/scenario/records-per-column.md'
          - Auto Generate From Data Connection: 'setup/guide/scenario/auto-generate-connection.md'
          - Delete Generated Data: 'setup/guide/scenario/delete-generated-data.md'
          - Generate Batch and Event Data: 'setup/guide/scenario/batch-and-event.md'
      - Data Sources:
          - Files (CSV, JSON, ORC, Parquet): 'setup/guide/scenario/first-data-generation.md'
          - Cassandra: 'setup/guide/data-source/cassandra.md'
          - Kafka: 'setup/guide/data-source/kafka.md'
    - Configuration: 'setup/configuration.md'
    - Connection: 'setup/connection/connection.md'
    - Generator:
      - Data Generator: 'setup/generator/generator.md'
      - Record Count: 'setup/generator/count.md'
      - Report: 'setup/generator/report.md'
    - Validation: 'setup/validation/validation.md'
    - Foreign Keys: 'setup/foreign-key/foreign-key.md'
    - Advanced: 'setup/advanced/advanced.md'
  - Use Case and Comparison:
    - 'use-case/use-case.md'
    - Business Value: 'use-case/business-value.md'
    - Comparison: 'use-case/comparison.md'
    - Roadmap: 'use-case/roadmap.md'
  - Pricing: 'pricing.md'
  - About:
      - 'about.md'
      - Terms of service: 'legal/terms-of-service.md'
      - Privacy policy: 'legal/privacy-policy.md'

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - open-in-new-tab

