site_name: Data Caterer Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
  nav:
    - Home: 'index.md'
    - 'Get Started': 'get-started/docker.md'
    - Generators: 'generators/generators.md'
    - Connections: 'connections/connections.md'
    - Advanced: 'advanced/advanced.md'
  palette:
    scheme: slate
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search

