site_name: Data Caterer Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
  palette:
    scheme: slate
nav:
  - Home: 'index.md'
  - 'Get Started': 'get-started/docker.md'
  - Generators: 'generators/generators.md'
  - Connections: 'connections/connections.md'
  - Samples: 'sample/index.md'
  - Advanced: 'advanced/advanced.md'
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - open-in-new-tab

