site_name: Data Caterer Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
  nav:
    Home: index.md
    Generators: tech/generators.md
    Connections: tech/connections.md
    Advanced: tech/advanced.md
